### ISSUE TITLE
New logo

### ISSUE THREAD

**Issue by nunojesus** [Arc676/Arc-Music-Player#4]
first I would like to congratulate you on your project, it seems to be a consistent project, I wonder if this player will have an application for android our is for desktop? If you want my help with graphic design just say it, I can design a logo and other stuff for your project, for free of course. Greetings

**Comment by Arc676** [comment]
Thanks for the feedback!

I'm not currently considering developing an Android version. There are, however, two ports of this for Linux (one using `gtkmm` and the other using Qt). The Gtk version is moving more smoothly and is the primary Linux port for now. In the future, the Qt version might become the Ubuntu Touch port.

The application already has an icon, which you can view in the repository. GitHub won't let you see the `icns` file directly, but you can check the `iconset` folder for the PNGs. However, if you feel so inclined, you're welcome to design a better one!

**Comment by nunojesus** [comment]
See if you like one of this logos that I design.
![ultimos](https://user-images.githubusercontent.com/34600369/39783040-c4da0b8a-530b-11e8-80fa-316f3b8f3f0a.png)

**Comment by Arc676** [comment]
Those are pretty good! But I think I prefer one without text.

Could you try the top left one but without text and with the musical note in a darker color?

Additionally, I need the logo to be at least 1024x1024 for icon creation. 

Second, could you specify a license for this artwork? I personally like CC licenses, but you are free to choose any open license.

**Comment by nunojesus** [comment]
Look if it good like this?

I can make the logo 1024x1024, this artwork is licensed under a [Creative Commons Attribution 4.0 International License.](https://creativecommons.org/licenses/by/4.0/)

![music](https://user-images.githubusercontent.com/34600369/39810611-8bf9cd74-537d-11e8-951c-0503d2a0efe1.png)

**Comment by nunojesus** [comment]
If everything is ok with the design I will prepair the png files

**Comment by Arc676** [comment]
Looks good! Just one file is enough, I have a tool that scales down automatically. Feel free to open a PR.

**Comment by nunojesus** [comment]
Link of editable files

https://drive.google.com/drive/folders/1YQKOAzad_Djn4dCVnGxZ_BucjWaBfuA0
