### ISSUE TITLE
logo design

### ISSUE THREAD

**Issue by rezarezz** [Arc676/Arc-Music-Player#7]
Hello sir, I'm a graphic designer and I would love to contribute to your project with a logo. This is completely free, take it as a contribution. In case you agree I would be presenting sketches and you will be choosing/modifying the aspects you like more so we could work on the perfect logo for your project together.

Let me know what do you think? best regards :)

**Comment by Arc676** [comment]
Thank you for your interest in this project. However, a logo has already been designed as described in #4. 

If you’re interested in more logo design, most of my other projects are in need of one as well. Any other repository with a `macos` tag except Pong and PlateCodes need a logo.
